### ISSUE TITLE
MFHD Suppression by Location

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/marc_liberation#1]
A MFHD can be suppressed in two ways:
1. `MFHD_MASTER.SUPPRESS_IN_OPAC='Y'`
2. By being associated with a suppressed location, something like:
   
   ``` sql
   SELECT *
   FROM mfhd_master 
     INNER JOIN location
       ON location.location_id = mfhd_master.location_id
   WHERE location.suppress_in_opac = 'N'
   AND mfhd_master.suppress_in_opac = 'N'
   ```

Right now we're only handling the first case.

**Comment by christinach** [comment]
no longer valid given the Alma migration
