### ISSUE TITLE
Use new /alma drive on lib-sftp

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#1000]
Configure publishing jobs to write to `/alma/publishing` since we expect to receive other data on this server.

Configure file transfer jobs to check that location, as well.

Run an end-to-end test.

**Comment by mzelesky** [comment]
I have updated the publishing profiles in Alma to utilize the new folder. Anna also created the directory on lib-sftp, so the job should be ready to republish when the rest of the configuration is done (the file transfer jobs).

**Comment by hackartisan** [comment]
end-end test successful.
