### ISSUE TITLE
Can we index the 050 and 090? Indexing the 050/090 lc call_number from the bib record.

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#1017]
Index 050/090 from bibliographic records for collection development purposes.

**Comment by mzelesky** [comment]
Principal concern:

If a non-LC call number is in a holding, but the bib record has an LC call number in the 050, the bib record would appear in the call number browse in 2 locations. In the case of a physical location, a patron could mistakenly search for the item on the shelf at the place the LC call number says it will be, even though the book is actually shelved with the call number in the holdings.

To best serve all uses, the LC call number from the bib record should be indexed separately, and searchable from the main search bar, but not included in the call number browse. A possible label for this search is 'LC Call Number Starts With'.

The bibliographic LC call number will only appear in the record display page in the 'Details' section, below the subjects. The label of the field would be 'LC call number'. Executing a search based on this call number should NOT direct the user to a browse, but function more like the subject links (without the browse functionality).

Criteria:
1. Evaluate all call numbers on the 852 fields to see if they are LC call numbers (using Lcsort). All LC call numbers from the 852 fields should display in the Details section. No LC call numbers should be evaluated from the bib record if there is at least one valid LC call number found.
2. If there are no valid LC call numbers from the holdings, look for the first 090 field in the bib record that has a valid LC call number. If there are no valid LC call numbers in the 090 fields, no 050 fields should be evaluated.
3. If there are no 090 fields, return the first valid LC call number from the 050 fields.
4. If there are no LC call numbers after this process, do nothing.

**Comment by christinach** [comment]
Closing this issue. Discussed with dssg and there are better ways to get an analytics report directly through alma.
