### ISSUE TITLE
Solr in Lando

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/marc_liberation#1019]
The Solr admin screen does not show the list of fields in the Solr dev and Solr test in Lando. See screenshot below. 

~~Is this by design or an oversight?~~ [UPDATE: this drop down list is in fact enabled, it just took a long time to load the very first time. However, there is indeed an error in the solrconfig.xml that causes Solr to log errors on initialization, these errors are documented below on this ticket]

![solr_lando](https://user-images.githubusercontent.com/568286/106296499-c0051980-621f-11eb-9280-51a21788333b.png)

**Comment by tpendragon** [comment]
This isn't on purpose. I've seen this happen when there's a broken field or something.

**Comment by hectorcorrea** [comment]
A broken field in Solr, like a bad solrconfig.xml or schema.xml ?

**Comment by hectorcorrea** [comment]
It seems that I can indeed click on the fields on the Schema and browse through the fields. I thought I couldn't (?)

But I also noticed that the Solr log is showing up and error on some of the fields defined in `solrconfig.xml`. The error says:

```
2/1/2021, 2:35:17 PM | ERROR true | x:marc-liberation-core-development | RequestHandlerBase | 
org.apache.solr.common.SolrException:  org.apache.solr.search.SyntaxError: 
Cannot parse  'cataloged_tdt:[NOW/DAY-7DAYS NOW/DAY+1DAY]': Encountered "  <RANGE_GOOP> "NOW/DAY+1DAY "" at line 1,&#8203; column 29.

org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: 
Cannot parse 'cataloged_tdt:[NOW/DAY-7DAYS NOW/DAY+1DAY]': Encountered " <RANGE_GOOP> "NOW/DAY+1DAY "" at line 1, column 29. 

Was expecting:     "TO" ...      	at 

org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:218) 	at 
...
java.base/java.lang.Thread.run(Unknown Source) Caused by: org.apache.solr.search.SyntaxError: 
Cannot parse 'cataloged_tdt:[NOW/DAY-7DAYS NOW/DAY+1DAY]': Encountered " <RANGE_GOOP> "NOW/DAY+1DAY "" at line 1, column 29.
```

These fields are defined as follow:

```
        <lst><str name="fq">cataloged_tdt:[NOW/DAY-7DAYS NOW/DAY+1DAY]</str></lst>
        <lst><str name="fq">cataloged_tdt:[NOW/DAY-14DAYS NOW/DAY+1DAY]</str></lst>
        <lst><str name="fq">cataloged_tdt:[NOW/DAY-21DAYS NOW/DAY+1DAY]</str></lst>
        <lst><str name="fq">cataloged_tdt:[NOW/DAY-1MONTH NOW/DAY+1DAY]</str></lst>
        <lst><str name="fq">cataloged_tdt:[NOW/DAY-2MONTHS NOW/DAY+1DAY]</str></lst>
        <lst><str name="fq">cataloged_tdt:[NOW/DAY-3MONTHS NOW/DAY+1DAY]</str></lst>
        <lst><str name="fq">cataloged_tdt:[NOW/DAY-6MONTHS NOW/DAY+1DAY]</str></lst>
```

It seems like Solr expects a `TO` statement between the ranges `cataloged_tdt:[NOW/DAY-6MONTHS TO NOW/DAY+1DAY]`

**Comment by hackartisan** [comment]
@hectorcorrea The configs are refreshed manually from the pul_solr repo via this rake task: https://github.com/pulibrary/marc_liberation/blob/alma/lib/tasks/dev.rake#L40

The way to fix this error would probably be to fix it in the [staging config in pul_solr](https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-staging/conf/solrconfig.xml#L156-L162), deploy that config and check that it's good, then fix it in the [production](https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-production/conf/solrconfig.xml#L156-L162) and [production-alt](https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-production-alt/conf/solrconfig.xml#L156-L162) configs in pul_solr and merge all those, then run the rake task above to pull in the fix to lando / circleci here in marc liberation.

**Comment by hectorcorrea** [comment]
I am having a hard time getting the error to be logged again and the I noticed that the [offending Solr config values](https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-staging/conf/solrconfig.xml#L156-L162) are section 

```
<listener event="newSearcher" class="solr.QuerySenderListener">
```

What or who uses this listener?

**Comment by hackartisan** [comment]
I think newsearcher is fired whenever solr starts a new searcher object. So you would put things here to warm caches that you expect to be used, like common facets or common search queries.

**Comment by hectorcorrea** [comment]
@hackartisan the config in catalog-staging seems to be busted. It includes a duplicate section for the `updateHandler/updarteLog` setting and Solr refuses to create the core with it. This duplicate section seems to be pretty new. 

Section at the top: https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-staging/conf/solrconfig.xml#L34-L38

Duplicate section at the bottom: https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-staging/conf/solrconfig.xml#L529-L533)

I can remove the duplicate section [as I submit a new solrconfig.xml](https://github.com/pulibrary/pul_solr/pull/253) to fix the original issue with the bad date range in it, but I am not sure I am reading this right.

Any thoughts?

**Comment by hectorcorrea** [comment]
I've submitted at PR that will allow us to [download a specific set of config files](https://github.com/pulibrary/marc_liberation/pull/1056) e.g. production vs staging, and another PR that [fixes the config in the staging files](https://github.com/pulibrary/pul_solr/pull/253). 

If that works, then I can submit a separate PR to fix the production and production-alt environments.

**Comment by hectorcorrea** [comment]
The config in `catalog-staging` in pul_solr has been fixed in https://github.com/pulibrary/pul_solr repo. I still need to update `catalog-production` and `catalog-production-alt`.

@hackartisan what config files do we want to keep in the `./solr/config` folder of this (marc_liberation) repo? A copy of catalog-staging, catalog-production, or catalog-production-alt ?

**Comment by hackartisan** [comment]
@hectorcorrea On a broad time scale there shouldn't be a difference between the 3; they exist for short-term discrepancies (i.e. testing config changes or index migration needs). Probably makes sense to use whichever one the catalog is currently running in production (looks like catalog-production-alt, although that one should be identical to catalog-production).

**Comment by hectorcorrea** [comment]
Closed via https://github.com/pulibrary/marc_liberation/pull/1086
