### ISSUE TITLE
Dump data doesn't persist on deploys

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#105]
Capistrano only keeps files from the 5 most recent deploys. As we've been doing a lot of work marc_liberation lately, the least recent deploy is from Monday. All dump files from before then are no longer available (i.e any full Voyager dumps, like the one completed this [past Sunday](https://bibdata.princeton.edu/dumps/1046.json)). `data/` should be made a shared directory so it can persist on future deploys.

**Comment by jpstroop** [comment]
Uhhh...I'll need to double check, but that machine _should_ have a separate filesystem (which much more storage available for the dumps) mounted at `/data`. It should never have been in the cap managed directories in the first place.

**Comment by tampakis** [comment]
Just changed the data directory in the config from `data` to `/data/marc_liberation_files`. Should fix this issue.
