### ISSUE TITLE
Discharge an item

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_liberation#1072]
For SCSB, we need the ability to discharge an item from the ReCAP circulation desk.

SCSB is aware of the MMS Id, Holding Id, and Item Id, so it should not require an item lookup by barcode before doing it.

proposed route: `post /bibliographic/:mms_id/holdings/:holding_id/items/:item_id/discharge`

The endpoint should require a valid, hard-coded auth token.

The alma endpoint to use is as follows. Note that the values provided for these parameters won't vary, just the ids sent in the api path.
```
url = 'https://api-na.hosted.exlibrisgroup.com'
response = alma_conn(url).post do |req|
  req.url 'almaws/v1/bibs/9968643943506421/holdings/22258767470006421/items/23258767460006421'
  req.headers['Content-Type'] = 'application/json'
  req.headers['Accept'] = 'application/json'
  req.params['apikey'] = [key]
  req.params['op'] = 'scan'
  req.params['external_id'] = 'false'
  req.params['library'] = 'recap'
  req.params['circ_desk'] = 'DEFAULT_CIRC_DESK'
  req.params['done'] = 'true'
end
```

**Comment by tpendragon** [comment]
If there are required params should we do something like `post '/bibliographic/:mms_id/holdings/:holding_id/items/:item_id/discharge`? Seems like that would leverage more of Rails' handling of params.

**Comment by hackartisan** [comment]
👍🏻 that sounds good to me.
