### ISSUE TITLE
Bibdata Dev Domain

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#132]
Spin up a bibdata-dev.princeton.edu host to use for testing/demonstration purposes.

**Comment by jpstroop** [comment]
Phil was working on this--maybe you've been speaking to him?

**Comment by kevinreiss** [comment]
No, I hadn't. I had an alias created for it. I'll advise him and let him know it can switched over when the env he is working on is ready.

**Comment by kevinreiss** [comment]
Hey, this exists.
