### ISSUE TITLE
JSONLD Internal Server Error

### ISSUE THREAD

**Issue by escowles** [pulibrary/marc_liberation#160]
I'm seeing an Internal Server Error when trying to retrieve JSONLD, but the record otherwise works normally.  So this fails: https://bibdata.princeton.edu/bibliographic/3499523/jsonld but this works: https://bibdata.princeton.edu/bibliographic/3499523/solr

Sample records: 3499523 3512354 4602068

**Comment by tampakis** [comment]
3499523 - has a language code of 'ang' which isn't included in the languages.yml, looking into using the iso-639 gem
4602068 - 'gmh' is Middle High German
3512354 - 'ang'
