### ISSUE TITLE
Can't parse URIs with spaces

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#167]
https://pulsearch.princeton.edu/catalog/9706229
Escape URI before parsing it.

**Comment by jpstroop** [comment]
Which URI do you mean?

**Comment by tampakis** [comment]
Electronic access in the 856. It's a quick fix.

**Comment by jpstroop** [comment]
I think they should fix the data. We're going to wind up double-encoding/escaping URIs if we're not careful.

**Comment by tampakis** [comment]
They are doing that too, but `URI.escape` looks safe.

**Comment by tampakis** [comment]
Actually, that seems like a bad idea. I'll just handle the case of whitespace specifically.
