### ISSUE TITLE
General Barcode Lookup on Bibdata 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#171]
In addition to the work to provide a ReCAP friendly export by barcode https://github.com/pulibrary/marc_liberation/commits/barcode_lookup we should also provide a general lookup by barcode that produces a reasonable. The legacy getVoyRec in use in various utilities provides this lookup, http://libweb5.princeton.edu/getvoyrec/.

**Comment by mzelesky** [comment]
The method I have created works for all barcodes. The one difference is that ReCAP materials have the 852 $h and $i merged and additional subfields are added to the 876 for ReCAP-specific information. Is that sufficient, or does a method need to be created that omits the extra ReCAP-specific fields even for ReCAP records?

**Comment by kevinreiss** [comment]
I will try and identify if any applications actually utilize the barcode lookup present in GetVoyRec.
