### ISSUE TITLE
JSONLD uses undefined "genre" property

### ISSUE THREAD

**Issue by escowles** [pulibrary/marc_liberation#182]
There is no "genre" property in DC or DC Terms — we should be using dc:type instead.

**Comment by jpstroop** [comment]
Where are these mapped from? Wondering about [`dct:medium`](http://dublincore.org/documents/dcmi-terms/#terms-medium).

**Comment by jpstroop** [comment]
I never quite know what to do w/ dc's format, type and medium vs. MARC's notions of form and genre

**Comment by jpstroop** [comment]
Merging, will make a new ticket.
