### ISSUE TITLE
JSONLD uses undefined "note" property

### ISSUE THREAD

**Issue by escowles** [pulibrary/marc_liberation#185]
It looks like the JSONLD is using both dce:description and an undefined "note" property for notes.  The dce:description is coming from 520, and the "note" is coming from 500/590.  See e.g., https://bibdata.princeton.edu/bibliographic/4822276/jsonld

**Comment by escowles** [comment]
So we have at least three notes:
* Plum description => dct:abstract
* 520 => dce:description
* 500/590 => "note" — do we want to lump these in with the 520 notes?

**Comment by jpstroop** [comment]
I think all 5xxs except for 520 should go to dc:description for now, and 520 should go to dc:abstract. I think there's one or two 5xxs we're not supposed to display at all (@tampakis?), but that's probably already filtered out.

**Comment by escowles** [comment]
Do we want to use the 520 notes instead of having a separate description field in Plum?  Or do we want to keep a separate description field in Plum, and use a different predicate for it?

**Comment by jpstroop** [comment]
I thought the original idea was to populate the abstract field in Plum with the text from the 520 if it exists.

**Comment by escowles** [comment]
OK, that's reasonable — just not what we're doing now.  I'll update the PR to do that.
