### ISSUE TITLE
404 Error when Patron route receives an ID it can't find.

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#212]
Currently when an ID that can't be found in Voyager is passed (https://bibdata.princeton.edu/patron/blah) you get a 500 error returned. Should we return a 404 error instead?

**Comment by jpstroop** [comment]
Yes. I feel like that was the case at some point, so this may be a bug.

**Comment by kevinreiss** [comment]
Yeah, looks like https://github.com/pulibrary/marc_liberation/blob/0c945be3215c6ecb9025a1edad268604f9a219e6/app/controllers/patron_controller.rb#L6 we need to test for nil? rather than empty?.

**Comment by kevinreiss** [comment]
Fixed
