### ISSUE TITLE
Patron info lookup needs to exclude carrel barcodes

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_liberation#227]
See https://github.com/pulibrary/voyager_helpers/pull/61

Barcodes of the 'CAR1' and 'CAR2' patron groups need to be excluded from the patron lookup. @tampakis Any suggestions?

**Comment by kevinreiss** [comment]
@tampakis my only thought was that the hardcoded patron groups that are being excluded should be configured somewhere. If you aren't concerned about it let's proceed.

**Comment by kevinreiss** [comment]
@mzelesky @tampakis this is still an issue correct?

**Comment by mzelesky** [comment]
Closed by pulibrary/voyager_helpers#61
