### ISSUE TITLE
Need new barcode lookup for SCSB that includes suppressed records

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_liberation#237]
Some records in ReCAP have legitimate suppressed holdings (e.g., master copy of microforms, other dark storage), so suppressed bibs and holdings need to be returned for SCSB lookup. The current barcode lookup method is for "public" use, where one wouldn't want suppressed records to be returned, so another route needs to be created for SCSB lookup.

**Comment by kevinreiss** [comment]
Add this under the route "/scsb". Need to create new query in Voyager Helpers so we can return suppressed records.

**Comment by kevinreiss** [comment]
How is using ```/barcode/32101075573871/scsb```?

**Comment by tampakis** [comment]
sounds good to me
