### ISSUE TITLE
Allow Geo-Coordinates to be Extracted from SCSB Records

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#242]
Records with 034 fields like SCSB-4999437 - CUL

```
<marcxml:datafield tag="034" ind1="1" ind2=" ">
      <marcxml:subfield code="a">a</marcxml:subfield>
      <marcxml:subfield code="b">500000</marcxml:subfield>
      <marcxml:subfield code="d">W1570000</marcxml:subfield>
      <marcxml:subfield code="e">W1410000</marcxml:subfield>
      <marcxml:subfield code="f">N0731500</marcxml:subfield>
      <marcxml:subfield code="g">N0693000</marcxml:subfield>
    </marcxml:datafield>
```

are rejected by our current normalization routine in geo.rb. Can we adjust the current routine to extract something of value out of this?

NYPL Example ID - SCSB-6467370

**Comment by kevinreiss** [comment]
@tampakis we just decided to ignore this correct?

**Comment by tampakis** [comment]
yeah because they don't get used for anything, i don't think we even log them anymore.
