### ISSUE TITLE
Update availability to make recap hold request status unavailable

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#250]
Related to: https://github.com/pulibrary/voyager_helpers/issues/69
When an item has a status of "Hold Request":
 - [ ] Regular recap items should be unavailable
 - [ ] Rare "always requestable" recap items should still be available, see the ```aeon_location``` flag
 - [ ] All other locations should ignore this status

**Comment by kevinreiss** [comment]
Are there any complications with the ```Pending Order```, ```On Order```, or ```In Process``` statuses that could arise here?
