### ISSUE TITLE
Expand availability api to support scsb id and barcode lookup

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#251]
add additional params to the availability api to accept scsb id and barcode lookup. An "institution" param is also required to support the scsb id lookup.

Lookup by barcode: https://uat-recap.htcinc.com:9093/swagger-ui.html#!/shared-collection-rest-controller/itemAvailabilityStatus
Lookup by institution bib id and institutional identifier https://uat-recap.htcinc.com:9093/swagger-ui.html#!/shared-collection-rest-controller/bibAvailabilityStatus

**Comment by kevinreiss** [comment]
SCSB Client Mixin - may be of use https://github.com/pulibrary/requests/blob/recall_fixes/app/models/concerns/requests/scsb.rb. Need to set the ```SCSB_AUTH_KEY``` environment variable.

**Comment by kevinreiss** [comment]
took a stab at this in 9c93646ca167b91a474cab36553027b257df8f83
