### ISSUE TITLE
ReCAP Items and "Returned" Label

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#255]
Items with the status of 'Discharged' are not requestable SCSB. We show these as a green returned label in OL. Not sure if marc liberation is the place to solve this but noting the discrepancy here. 

```
[
  {
    "barcode": "32101088198906",
    "id": 1149588,
    "location": "rcppa",
    "copy_number": 1,
    "item_sequence_number": 1,
    "status": "Discharged",
    "on_reserve": "N",
    "label": "ReCAP"
  }
]```

**Comment by mzelesky** [comment]
This is something that will be addressed via Voyager System Administration. The 'Discharged' status will only appear for 5 minutes after an item is checked in for ReCAP items.

**Comment by kevinreiss** [comment]
Closing per voyager reconfiguration as described by @mzelesky.
