### ISSUE TITLE
Configure resque

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#30]
- [ ] Make daily updates higher priority than full dumps
- [ ] Have resque start up on system reboot
- [ ] Automate resque requeueing of failures? Mainly caused by the voyager daily reboot

Currently resque is run/configured as follows:

```
PIDFILE=./resque.pid COUNT=5 BACKGROUND=yes QUEUE=* bundle exec rake resque:workers >> log/resque.log 2>> log/resque.log
```

**Comment by kevinreiss** [comment]
https://github.com/pulibrary/plum/blob/master/config/deploy.rb#L61 use upstart scripts. Need workers to be refreshed upon shutdown/startup.

**Comment by tampakis** [comment]
We don't use resque any more.
