### ISSUE TITLE
Only index unique recap notes

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#303]
Blacklight handles the display properly, but currently dozens of identical recap notes get indexed.

**Comment by kevinreiss** [comment]
Are you talking about the ```recap_notes_display``` field? There is a helper defined to de-duplicate it https://github.com/pulibrary/orangelight/blob/bb9e0bd69a0a174748f556a7d278ef7a05ac8fc6/app/helpers/application_helper.rb#L528. Sorry, that should have been part of marc_liberation and not done at the BL level.

**Comment by escowles** [comment]
I don't know of any reason you'd want duplicate values in a Solr field.  It looks like this update basically calls `uniq` on every field, which seems reasonable to me.
