### ISSUE TITLE
Document How to Run Marc to Solr Locally

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#340]
Add to the README - from the project root directory:

1. Do this https://github.com/pulibrary/marc_liberation/blob/master/circle.yml#L8-L10.
2. Set the RAILS_ENV ```RAILS_ENV=test bundle exec rspec marc_to_solr/spec```

**Comment by hackmastera** [comment]
1 was added yesterday; 2 still needs to be added.
