### ISSUE TITLE
Add an availability property to /availability

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/marc_liberation#39]
See discussion on https://github.com/pulibrary/orangelight/pull/298#issuecomment-148752982

Presently, theses statuses should result in `available: false`:

> At Bindery
Claims Returned
Charged
Hold Request
In Transit
Lost
Missing
On Hold
Overdue
Recall Request
Remote Storage Request
Renewed
Withdrawn

**Comment by tampakis** [comment]
Mapping of statuses to labels is to be done in Orangelight.
