### ISSUE TITLE
Identifier no longer showing in JSON-LD

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/marc_liberation#401]
See: https://bibdata.princeton.edu/bibliographic/10002695/jsonld

Our identifiers to reconcile report depends on that field existing. Is it gone for a particular reason? There's a references now..

**Comment by jrgriffiniii** [comment]
The "3" subfield for "856" in the record for referenced seems to be what triggers this:
https://bibdata.princeton.edu/bibliographic/10002695

**Comment by tpendragon** [comment]
Reopening because https://bibdata.princeton.edu/bibliographic/4031016/jsonld is still not showing identifier.

**Comment by tpendragon** [comment]
We may be able to pull the extra identifiers out of the `iiif_manifest_paths`
