### ISSUE TITLE
Make incremental updates higher priority than full dumps

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#419]
Currently when we run a full Voyager export (like on July 13), it starts at 5am and takes most of the day to complete. Because we don't have any priority set up on the sidekiq queue, the full dump and incremental update jobs go on the same default queue. When the incremental jobs are queued at 10am and 2pm they don't finish in time for the scheduled Solr update (about 40 minutes later). This causes the updates to be missed.

Set up a higher priority queue for the incremental updates. This requires a bit of a code refactor because both the incremental and full exports run the same [dump_bib_records](https://github.com/pulibrary/marc_liberation/blob/master/app/models/dump.rb#L33-L36) method.

**Comment by escowles** [comment]
👍 thanks for tracking this down @tampakis!

I see the queues `default`, `low`, and `super_low` in Sidekiq, so I think this is probably as easy as setting an environment variable when doing a full dump, and then some logic in that Rake task to use the `super_low` queue when that variable is set.
