### ISSUE TITLE
Fix spec that fails in CircleCI 2.0

### ISSUE THREAD

**Issue by escowles** [pulibrary/marc_liberation#425]
This test fails in CircleCI 2.0 but passed in 1.0 just fine:

https://github.com/pulibrary/marc_liberation/pull/423/commits/6aae78c3f9406d3757f61d240cede6156b8a4cb5#diff-7631448fe51ab3ceea29762fc0df7990R24

**Comment by eliotjordan** [comment]
It's fixed now. 

https://github.com/pulibrary/marc_liberation/blob/main/spec/controllers/bibliographic_controller_spec.rb#L25
