### ISSUE TITLE
[Bibdata/production] OCIError: ORA-01722: invalid number

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/marc_liberation#437]
## Backtrace

    line 14 of [PROJECT_ROOT]/app/controllers/availability_controller.rb: index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/35827692)

**Comment by eliotjordan** [comment]
This is still an issue.

**Comment by escowles** [comment]
Dupe of #449
