### ISSUE TITLE
Chosen ARK is sometimes wrong

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/marc_liberation#447]
See https://bibdata.princeton.edu/bibliographic/7849625/jsonld

It's picking the last ARK (http://arks.princeton.edu/ark:/88435/cj82k733w) when it should be picking the first (http://arks.princeton.edu/ark:/88435/df65v9145).

This is causing pulibrary/figgy#1741.

**Comment by escowles** [comment]
Maybe lookup ARKs and include the destinations in the JSON-LD?

**Comment by jrgriffiniii** [comment]
As stated in https://github.com/pulibrary/figgy/issues/1741#issuecomment-416753612, this was resolved by https://github.com/pulibrary/marc_liberation/pull/452
