### ISSUE TITLE
Holding records 8xx fields

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#46]
@joycebcat at currently we only pull the 852s from the holding records into the Blacklight holdings block. Should we include additional fields in 850-880?
We currently are including 856, 866, 867, and 868 from the bilbiographic record. Would we ever want to strip these out from the bib record (like we do with the bib 852s?). I know that most of the time the 856 in the bibliographic matches with the elf locations. However this isn't always true.

In bib [4609321](http://pulsearch-dev.princeton.edu/catalog/4609321) the [bib 856s](http://bibdata.princeton.edu/bibliographic/4609321) don't correspond to an online [holding location](http://bibdata.princeton.edu/bibliographic/4609321/holdings). In this case there is no way to match up the links to the holdings with certainty. The holding record also has an 866 field not present in the bib record.

In bib [7617477](http://pulsearch-dev.princeton.edu/catalog/7617477), there are 856s in the [holdings record](http://bibdata.princeton.edu/bibliographic/7617477/holdings) which are different from the [bib record's](http://bibdata.princeton.edu/bibliographic/7617477) 856s.

**Comment by jpstroop** [comment]
Just to clarify this:
> In bib [4609321](http://pulsearch-dev.princeton.edu/catalog/4609321) the [bib 856s](http://bibdata.princeton.edu/bibliographic/4609321) don't correspond to an online [holding location](http://bibdata.princeton.edu/bibliographic/4609321/holdings). In this case there is no way to match up the links to the holdings with certainty. The holding record also has an 866 field not present in the bib record.

There are two holdings, and we've digitized both. There are descriptive notes about the holdings in each holding record, but the links to the digitized versions are in the bib record. The problem is that we don't have a way to know which link (`856`) should be associated with which holding.

I'm sure there are reasons why this is more difficult that it sounds, but to me the solution would be to put the `856`s in the holding records rather that the bib record.

(FWIW, longer term, I'd love see the PUDL or next iteration thereof become a separate holding location, so that we can facet on it just like any physical location--perhaps that's worth considering as part of this conversation?)

**Comment by jpstroop** [comment]
It's also worth noting that in the case of 4609321, there's probably a case to be made for the two holdings to be cataloged separately; one is a complete Gutenberg bible, and the other is a fragment, with different provenance, etc.

**Comment by kevinreiss** [comment]
@joycebcat are you saying that many of the PUDL items we have stored URLs in the catalog will *not* have one our "elf*" holding locations?

**Comment by joycebcat** [comment]
No, I'm saying that the cases where there are multiple 856s in the bib relating to different holdings records will be an issue with pudl material, and shouldn't/won't be a problem with anything else.

**Comment by joycebcat** [comment]
@tampakis The only "holdings" data we should harvest from the bib record is 856.  Yes, we should exclude other 86x fields from the bib--they will not apply to Princeton.  (To what extent to we use 867 and 868????)

**Comment by tampakis** [comment]
@joycebcat this is what I took from the Voyager config file: https://github.com/pulibrary/orangeindex/blob/development/lib/traject_config.rb#L842-L876
The 867 populates a field called "Supplements" and the 868 populates a field called "Indexes." At the very least I need to make sure that these fields only get included from the mfhd.

**Comment by joycebcat** [comment]
@tampakis OK. Thanks.
