### ISSUE TITLE
For incremental update rake tasks, allow timestamp to be set

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#477]
Most of the time when we run incremental updates, both from Voyager and from SCSB partner updates, we take all updated records from the last time the incremental update task was run. However, in times where there are unexpected errors, or the first time a process is run, it is helpful to be able to set a time/date and then process all updates since that time.
Example, updates from scsb since May: https://bibdata.princeton.edu/dumps/7970.json

**Comment by jrgriffiniii** [comment]
I have implemented some error handling and guard clauses (along with providing some additional test coverage) on https://github.com/pulibrary/marc_liberation/compare/issues-477-jrgriffiniii-rake-update-timestamp

I am sorry, but I am still struggling to understand precisely how these updates are applied.  On the `bibdata-worker` server nodes, I've found that there are various Rake Tasks invoked, notably `liberate:latest`.  Within this task, I've found that there are dump file locations provided to `IndexFunctions.update_records`:
```ruby
      IndexFunctions.update_records(dump).each do |marc_xml|
        IndexFunctions.unzip(marc_xml)
        sh "traject -c marc_to_solr/lib/traject_config.rb #{marc_xml}.xml -u #{solr_url}; true"
        File.delete("#{marc_xml}.xml")
        File.delete("#{marc_xml}.gz")
      end
```

(https://github.com/pulibrary/marc_liberation/blob/master/lib/tasks/orangeindex.rake#L151)

Are these the same dump files generated using the separate Rake Task [`marc_liberation:get_changes`](https://github.com/pulibrary/marc_liberation/blob/master/lib/tasks/sync.rake#L4)?  If so, https://github.com/pulibrary/marc_liberation/blob/master/app/models/dump.rb#L164 leads me to believe that many of the errors which should be handled are raised within [`VoyagerHelpers::SyncFu`](https://github.com/pulibrary/voyager_helpers/blob/master/lib/voyager_helpers/sync_fu.rb).  I look to proceed by focusing on this Gem if that is indeed accurate.
