### ISSUE TITLE
Make rake task to index scsb updates to Solr

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#479]
The incremental scsb updates are scheduled daily but don't get processed into Solr

**Comment by tampakis** [comment]
Look at the liberate:updates and liberate:latest tasks. They both will process updated records and deletes. The updates one can take an enviroment variable for a set date.

**Comment by hackmastera** [comment]
The dumps are in bibdata events listed as `Updated Partner ReCAP Records`

**Comment by tampakis** [comment]
This happens :)
