### ISSUE TITLE
Deploy new full reindex

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#481]
In doing a full reindex over the weekend there were intermittent timeout errors throughout the process causing the following update files ([167 total](https://bibdata.princeton.edu/dumps/8404.json)) to fail. 
```
3
14
26
31
52
53
56
64
68
79
86
91
92
94
110
135
```
Example error messages
```
2018-09-30T20:38:05-04:00 ERROR Could not add record 757992/757992 at source file position 31905: Solr error response: 503: {
  "responseHeader":{
    "status":503,
    "QTime":4007},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"No registered leader was found after waiting for 4000ms 
```
```
Solr response: 500: {
  "responseHeader":{
    "status":500,
    "QTime":5728},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.http.NoHttpResponseException"],
    "msg":"Failed synchronous update on shard StdNode: http://lib-solr1.princeton.edu:8983/solr/catalog-production_shard1_1_replica_n4/ update: org.apache.solr.client.solrj.request.UpdateRequest@2a9cef6b",
```

**Comment by hackmastera** [comment]
Brief searching suggested that perhaps we are oversharding. We're currently transitioning to collections with 2 shards, 3 replicas.

In case system / cpu load is related here, I created a datadog dashboard for the solr boxes: https://app.datadoghq.com/dash/934427/solr-boxes?live=true&page=0&is_auto=false&from_ts=1538419979092&to_ts=1538506379092&tile_size=m

Will close this ticket when transition to 2 shards, 3 replicas is complete.

**Comment by hackmastera** [comment]
I don't see any errors like the above in the full index we ran yesterday, on the new collection with 2 shards / 3 replicas.

**Comment by hackmastera** [comment]
This gist records connection errors observed in the log from a scsb update: https://gist.github.com/hackmastera/c11013a9d34b836eea3abeb610e2f9d8

The errors are linked to a maintenance window used for maintenance on the solr boxes. we should make sure we're not scheduling any work to run between 6:45 and 8:15am.

**Comment by hackmastera** [comment]
Started a new full index set.

Also added cron jobs to run updates 2x per day. First will run today (10/15) at around 4pm.

So we need to run updated records between then and the last full load (2018-10-13 5:00:11am).
