### ISSUE TITLE
008 dates should not assume "u" is "0"

### ISSUE THREAD

**Issue by escowles** [pulibrary/marc_liberation#536]
In this code:
https://github.com/pulibrary/marc_liberation/blob/master/marc_to_solr/lib/princeton_marc.rb#L59-L75

We are converting "u" to "0", but that results in nonsensical date ranges like "1976-1970" in https://catalog.princeton.edu/catalog/1170482

**Comment by tampakis** [comment]
the date_from_008 field should stay the same because it's the start of the range, but for the end_date_from_008 method maybe we should convert it to a 9?

**Comment by escowles** [comment]
Yes, converting "u" in the end dates to 9s seems like a reasonable way to make sure the ranges make sense and be reasonably faithful to the data.
