### ISSUE TITLE
move off mysql to postgresql

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/marc_liberation#541]
We've talked about moving off mariadb to postgresql. Leaving this here as an "enhancement".

**Comment by christinach** [comment]
- Update the database.yml to use postgres
- Update circleci with a postgres image
- Migrate location data
- Back up MySQL (mariaDB cluster). You could use https://github.com/yamldb/yaml_db
- Only include recent Voyager and SCSB updates (The page is too slow loading events from 2 years ago.)

**Comment by christinach** [comment]
1. Dump mysql on **production**:
      - mysqldump -u user -p password database_name > dump_file.sql  
1. In your local environment:
     1. make sure you are running mysql 5.7
     1. brew install pgloader (https://github.com/dimitri/pgloader)
     1. pgloader mysql://user:pass@localhost/marc_liberation_dev  postgresql://user:pass@localhost/marc_liberation_dev
      1. export a pg_dump
1. on bibdata-staging server
        - scp the pg_dump from your local
        - restore the pg_dump

**Comment by christinach** [comment]
1.Update the database name in the dump file to be the the db name on the box. (e.g `marc_liberation_staging` for `bibdata-staging`) 

2.Run the `bibdata-staging` playbook

3.Delete/create the `marc_liberation_staging` db on `lib-postgres3.princeton.edu`

4.on **bibdata-staging** server
   To restore the database on postgres run: `psql -U bibdata -d marc_liberation_staging -h lib-postgres3.princeton.edu -f /home/deploy/marc_liberation.dump`

5.On `lib-postgres3.princeton.edu` as postgres run `alter database marc_liberation_staging set search_path to marc_liberation_staging, public;` (this is specific to the `marc_liberation_staging` DB)

**Comment by carolyncole** [comment]
1. turn off bibdata2 on load balancer
1. ssh deploy@bibdata2
   1. cat app_configs/marc_liberation
   1. mysqldump -u user -p password marc_liberation_prod > dump_file.sql
1. On Christian's machine in master
   1.  change `config/database.yml` to have dev database name `marc_liberation_prod`
   1.  run `rake db:drop db:create db:migrate`

**Comment by christinach** [comment]
`delete_ids = Dump.where(dump_type: DumpType.find_by(constant: 'ALL_RECORDS')).order("id DESC").offset(3).pluck(:event_id)`
`delete_ids << Dump.where(dump_type: DumpType.find_by(constant: 'CHANGED_RECORDS')).order("id DESC").offset(35).pluck(:event_id)`
`delete_ids << Dump.where(dump_type: DumpType.find_by(constant: 'MERGED_IDS')).order("id DESC").offset(8).pluck(:event_id)`
`delete_ids << Dump.where(dump_type: DumpType.find_by(constant: 'PRINCETON_RECAP')).order("id DESC").offset(5).pluck(:event_id)`
`delete_ids.flatten!.compact!`
`Event.destroy(delete_ids)`
`event_ids_to_remove = Event.where('finish <  ?', "2019-11-04")`
`event_ids_to_remove.each(&:destroy)`

**Comment by christinach** [comment]
closed by #608
