### ISSUE TITLE
[Bibdata/production] Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#547]
## Backtrace

    line 19 of [PROJECT_ROOT]/app/services/ark_resolver.rb: initial_result
    line 23 of [PROJECT_ROOT]/app/services/ark_resolver.rb: final_result
    line 10 of [PROJECT_ROOT]/app/services/ark_resolver.rb: location

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/43410165)

**Comment by tampakis** [comment]
Hoping that the CDL can update the certificate for https://arks.princeton.edu. The catalog record displays the object correctly but I the metadata can't be updated in Figgy without the JSON-LD service https://catalog.princeton.edu/catalog/491472

**Comment by christinach** [comment]
https://bibdata.princeton.edu/bibliographic/3891312/jsonld
The 856 includes a bad ark url <subfield code="u">https://arks/princeton.edu/ark:/88435/t435gh92k</subfield>. I confirmed with @mzelesky and he updated to the correct one https://arks.princeton.edu/ark:/88435/t435gh92k. Thank you Mark!
