### ISSUE TITLE
[Bibdata] RSolr::Error::Http: RSolr::Error::Http - 404 Not Found
Error:     Not Found

URI: http://lib-solr.princeton.edu:8983/solr/catalog/update?wt=json
Request Headers: {"Content-Type"=>"application/json"}
Request Data: "{\"delete\":[\"6494462\",\"6899579\",\"6930354\",\"6931691\",\"6932449\",\"9931094\",\"9997642\",\"9997647\",\"9997650\",\"10248052\",\"10248054\",\"10248057\",\"10248059\",\"10248060\",\"10248062\",\"10248063\",\"10248066\",\"10395268\",\"10463973\",\"10464656\",\"10777603\",\"112252...

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/marc_liberation#562]
## Backtrace

    line 121 of [PROJECT_ROOT]/lib/tasks/orangeindex.rake: block (3 levels) in <top (required)>
    line 113 of [PROJECT_ROOT]/lib/tasks/orangeindex.rake: each
    line 113 of [PROJECT_ROOT]/lib/tasks/orangeindex.rake: block (2 levels) in <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/55049633)

**Comment by hackmastera** [comment]
This request is going to `catalog` which doesn't seem to be a collection or alias on solr. Cron jobs should be reviewed.

**Comment by hackmastera** [comment]
Looks like this was an ad-hoc run that just contained a typo; close this issue when that task has successfully been run again.

**Comment by tampakis** [comment]
Removed stale ad-hoc job
