### ISSUE TITLE
[Bibdata/production] ActiveRecord::StatementInvalid: Mysql2::Error: WSREP has not yet prepared node for application use: SELECT  `locations_holding_locations`.* FROM `locations_holding_locations` WHERE `locations_holding_locations`.`code` = 'elf1' LIMIT 1

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#572]
## Backtrace

    line 119 of [PROJECT_ROOT]/app/controllers/availability_controller.rb: get_holding_location
    line 204 of [PROJECT_ROOT]/app/controllers/availability_controller.rb: update_item_loc
    line 101 of [PROJECT_ROOT]/app/controllers/availability_controller.rb: block in single_bib_circulation

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/48392837)

**Comment by jrgriffiniii** [comment]
This was likely triggered by the MariaDB cluster/Percona difficulties - as this was an infrastructure issue, I'm going to close this.
