### ISSUE TITLE
Lookup by Barcode

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/marc_liberation#62]
Looking up an item by barcode is a use-case for the ReCAP middleware project. Will support the ReCAP accession process for newly acquired materials.

**Comment by kevinreiss** [comment]
@jpstroop @tampakis This lookup came up as a use-case for the ReCAP middleware project. Do you see any issues with providing an endpoint that can return bib/holding/item data back via a barcode.

**Comment by jpstroop** [comment]
Nope, that should be fine. I'd prefer that the service redirect to the `bibliographic/{bibid}` route rather  than return the data directly.

**Comment by kevinreiss** [comment]
Further review of this with @mzelesky indicates for the ReCAP export indicates we have a small, but non trivial amount of records that share a barcode. These are primarily "bound with" titles where multiple bib entities have distinct item records that point to the same barcode. Bad API design to default to a redirect when a barcode has a single bib/item but return a list of associated IDs in instances when the barcoe is shared?

**Comment by mzelesky** [comment]
As an example, here is a barcode:

32101049804451

It is attached to item id 3823589, and it has 8 bibs attached to it.

**Comment by jpstroop** [comment]
> Bad API design to default to a redirect when a barcode has a single bib/item but return a list of associated IDs in instances when the barcode is shared?

Yes. It'll add overhead, but maybe a 300 with all links in the body? I've never seen this done, but seems to be what Mr Fielding suggests:

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.1

(I was expecting to find a pattern based on 302 Found with multiple links and no Location header, and maybe there still is a more commonly implemented pattern out there, but it seems like this is what 300 was meant for)

**Comment by mzelesky** [comment]
There are also ~21,000 barcodes that are shared with multiple item IDs (yikes!).

**Comment by kevinreiss** [comment]
@mzelesky is going to work on a query for Voyager Helpers that is appropriate and then we can take a pass at implementing the pattern @jpstroop suggests for web endpoint.

**Comment by mzelesky** [comment]
As a point of clarification:

"bound with" materials share one holdings and attached items. The ~21,000 barcodes I identified are shared by distinct items. I just re-ran my query, though, and it's actually only ~1,300. I must have omitted a Group By. My apologies. So it's not as bad as I thought it was.

I just got off the phone with Marie, and she explained there is no case where it is correct to have multiple items that share a barcode. So it is something her staff will have to address this summer (when end-of-the-year shelving is done).

**Comment by kevinreiss** [comment]
Okay, HTC had two purposes for asking for a lookup by barcode. They wanted to get the real-time item status of any given barcode from the item record and also be able to fetch bib/holdings data by barcode during the accession process for new records.
