### ISSUE TITLE
Determine how holdings with no items behave in Alma

### ISSUE THREAD

**Issue by kelynch** [pulibrary/marc_liberation#642]
Determine how holdings without items associated behave in Alma.  We will need sample records loaded into the Alma sandbox that meet this criteria to test.

When requesting, if there are no items there is a different request route.

Secondly, the status of an item will be different if there are no items.

**Comment by mzelesky** [comment]
There is no possibility of holdings with no items in Alma. Instead, Alma auto-generates barcodes if no items exist in an incoming holding.

**Comment by mzelesky** [comment]
So, we need to develop logic for looking at the barcodes attached to items to determine if the order status needs to be presented.

**Comment by mzelesky** [comment]
https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/040Resource_Management/080Configuring_Resource_Management/140Configuring_the_Barcode_Generation_Method_and_Barcode_Validation

**Comment by hackartisan** [comment]
In voyager, if there's a holding with no item we retrieve the order status. In Alma there will be an item on the holding. If there is a real barcode it's an item. If there's a "temporary" barcode it's provisional (e.g. on order).

Real barcodes all begin with 32101 and are codabar formatted. The others will have a prefix (the barcode will start with text).
