### ISSUE TITLE
Full reindex. Make sure this ad hoc job of a full dump would include the availability. 

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#649]

**Comment by kelynch** [comment]
Enrichment configurations for physical, electronic, and digital address this need - https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/030Resource_Management/080Publishing_and_Inventory_Enrichment
