### ISSUE TITLE
Configure incremental dump to dump files instead of publish to OAI

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#651]

**Comment by kelynch** [comment]
It looks like this is a duplicate of https://github.com/pulibrary/marc_liberation/issues/649 and https://github.com/pulibrary/alma_experimentation/issues/10.  Can we close this one?

**Comment by kelynch** [comment]
FTP server information is on LastPass.

**Comment by hackartisan** [comment]
Just did this. 

for posterity, here is an alma documentation page https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/030Resource_Management/080Publishing_and_Inventory_Enrichment
