### ISSUE TITLE
Recall functionality 

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#652]

**Comment by christinach** [comment]
How many recalls we have per year?

**Comment by kelynch** [comment]
According to findings in 5/12/20 Alma stand-up, it looks like we have ~228 per year.

**Comment by kelynch** [comment]
Implementation priority is reflected in the project plan, requirement + R030 (https://docs.google.com/spreadsheets/d/1gMS4bDebuqeToWBLNvBSilPYr7JP8zoX3PRXsebX-3w/edit#gid=0).  Closing this issue.

**Comment by hackartisan** [comment]
This was slotted in the project plan as "not needed" - closing
