### ISSUE TITLE
Add patron_group_charged to "items" hash of bibliographic/[bibid]/items

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/marc_liberation#704]
Value should be "Y" or "N"

Blocked by final approval of voyager workflow, specific cdl location decision, and cdl patron group.

**Comment by escowles** [comment]
Current plan: each branch will have a CDL user, and this value can be decided by checking whether the item is checked out to any of those users.

**Comment by christinach** [comment]
In voyager-helpers we added on the item level `patron_group_charged`: 'CDL'. https://bibdata-staging.princeton.edu/bibliographic/7991903/items.
