### ISSUE TITLE
Get a bib record from ALMA

### ISSUE THREAD

**Issue by kelynch** [pulibrary/marc_liberation#709]
Write a method that returns a bib record's MarcXML metadata from ALMA.

### For reference:
* [Sample Voyager MarcXML payload (8637182) ](https://raw.githubusercontent.com/pulibrary/marc_liberation/master/spec/fixtures/8637182.mrx)
* [Sample Voyager MarcXML payload (6815537) ](https://raw.githubusercontent.com/pulibrary/marc_liberation/94c77e2c582178c977ec7cafcf3a21aa42f52d8c/spec/fixtures/6815537.mrx)
* [Bib record GET methods in VoyagerHelpers](https://github.com/pulibrary/voyager_helpers/blob/0d8f633f1fbf258331cbf64baec4ba937f999224/lib/voyager_helpers/liberator.rb#L898-L920)

**Comment by christinach** [comment]
![ezgif com-video-to-gif(8)](https://user-images.githubusercontent.com/9905193/88399481-f192b900-cd94-11ea-8bfb-d6fad1634586.gif)

**Comment by christinach** [comment]
See https://github.com/pulibrary/marc_liberation/pull/717/files#diff-5a4958092b9453a04d6d03f0dec27e94R18-R29
