### ISSUE TITLE
Determine if a bib is suppressed in ALMA

### ISSUE THREAD

**Issue by kelynch** [pulibrary/marc_liberation#710]
Write a boolean method to determine if a bib is suppressed in ALMA.

We can work with @mzelesky to find an example in the sandbox.

**Comment by christinach** [comment]
`suppressed mms_id: 99222441306421` <suppress_from_publishing>true</suppress_from_publishing>

1. For the indexing, we need to check the `950 $a` (per @mzelesky ), to determine whether or not to index the bib. 

2. For indexing the associated holdings of a bib we need to check  the `952 $e` to determine whether or not to index the holding.  

3. Do we want suppressed bibs to be returned by Bibdata (https://bibdata.princeton.edu/bibliographic/11548314)? How will this impact other services (e.g . figgy @kelynch  @tpendragon @hackmastera  )

**Comment by tpendragon** [comment]
It won't hurt Figgy for suppressed bibs to be returned by bibdata, but bibdata has no auth mechanism - so I think if we're suppressing them for some reason they shouldn't be generally available?
