### ISSUE TITLE
Return a bib's holdings from ALMA

### ISSUE THREAD

**Issue by kelynch** [pulibrary/marc_liberation#711]
Write a method that return's a bib record's holdings from ALMA.

### For reference
* [Sample bib MarcXML from Voyager (1234567)](https://raw.githubusercontent.com/pulibrary/marc_liberation/master/spec/fixtures/1234567.mrx)
* [Sample holdings XML from Voyager (1234567)](https://raw.githubusercontent.com/pulibrary/marc_liberation/master/spec/fixtures/1234567-holdings.xml)

**Comment by christinach** [comment]
The response of /almaws/v1/bibs/{mms_id}/holdings is not a marc record. Currently we use it only on the homepage so we don't need to change it to a marc record. We will keep the xml response from alma.
This is the 'Get Holdings by Bibid' on the homepage.

See https://github.com/pulibrary/marc_liberation/issues/747

**Comment by christinach** [comment]
see https://github.com/pulibrary/marc_liberation/pull/717/commits/cfb3e2cccf3404c9150a40187b5197b63034502e
