### ISSUE TITLE
Export a general publishing schema of the alma fields

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#714]

**Comment by pmgreen** [comment]
Didn't find export options through the GUI or API so wrote a simple HTML scraper (downloaded the page and scraped it using Nokogiri). Sent values to @christinach

**Comment by christinach** [comment]
Thank you @pmgreen ! I copied the content in a txt file on google drive https://drive.google.com/drive/folders/0ACgqrvF40vkeUk9PVA
