### ISSUE TITLE
Add alma implementation for bibliographic#bib_holdings

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#733]
GET      /bibliographic/:bib_id/holdings(.:format) bibliographic#bib_holdings 
Based on the holding_id (we are doing this with voyager):
Where is 'Get a holding Record' being used? `https://bibdata.princeton.edu/holdings/1234567`, `/holdings/:holding_id'`
Where is 'Get item Records' being used? `https://bibdata.princeton.edu/holdings/1234567/items`, `/holdings/:holding_id/items`

Alma requires the `mms_id` and the `holding_id` to retrieve holdings record. https://developers.exlibrisgroup.com/console/?url=/wp-content/uploads/alma/openapi/bibs.json#/Catalog/get%2Falmaws%2Fv1%2Fbibs%2F%7Bmms_id%7D%2Fholdings%2F%7Bholding_id%7D

Alma requires the `mms_id` and the `holding_id` to retrieve items list. (In this case if the holding_id=ALL it will return all the holdings for the mms_id) https://developers.exlibrisgroup.com/console/?url=/wp-content/uploads/alma/openapi/bibs.json#/Catalog/get%2Falmaws%2Fv1%2Fbibs%2F%7Bmms_id%7D%2Fholdings%2F%7Bholding_id%7D%2Fitems

Add a form to retrieve holdings for a bib. (it returns the response from the api call. not xml)
https://bibdata-staging.princeton.edu/bibliographic/991227850000541/holdings?adapter=alma returns the response of the rest api call but not in xml.

Search if we want the response to be returned in xml. Otherwise close the issue as done. I've searched only orangelight, marc_liberation and requests and it's not being used.

**Comment by jrgriffiniii** [comment]
I've made some progress with the XML-serialization for this, however, I've yet to finish mapping the Alma XML schema to the one expected from bibdata clients: https://github.com/pulibrary/marc_liberation/compare/alma...issues-733-jrgriffiniii-bib_holdings

**Comment by jrgriffiniii** [comment]
As discovered by @hackartisan, the endpoint exposed for this is not often requested: https://app.datadoghq.com/logs/analytics?agg_q=%40controller%2C%40action%2C%40format&cols=host%2Cservice%2C%40http.url_details.queryString.q%2C%40action%2C%40format&from_ts=1604271119706&index=&live=true&messageDisplay=inline&query=source%3Aruby+service%3Abibdata+-%40controller%3A%22Locations%3A%3AHoldingLocationsController%22+-%40controller%3A%22Locations%3A%3ADeliveryLocationsController%22+-%40controller%3A%22HighVoltage%3A%3APagesController%22++-%40controller%3A%22Users%3A%3AOmniauthCallbacksController%22&stream_sort=desc&to_ts=1606863119706&top_n=10&viz=query_table

As such, I'm going to proceed by moving to close this. Please freely reopen this if one feels that this was done in error.

**Comment by christinach** [comment]
@jrgriffiniii I'm sorry I forgot to mention in the today's checkin that https://bibdata.princeton.edu/bibliographic/991227850000541/holdings?adapter=alma was already implemented to return the json response from the alma API call. The reason was that I also didn't find it to be used across the other apps but still wanted to return the information in json.

**Comment by christinach** [comment]
https://github.com/pulibrary/marc_liberation/blob/24e9b0f16dd242970c25a7d9417d51ee10a7a28b/app/controllers/bibliographic_controller.rb#L76

https://github.com/pulibrary/marc_liberation/blob/24e9b0f16dd242970c25a7d9417d51ee10a7a28b/app/adapters/alma_adapter/bib.rb#L43
