### ISSUE TITLE
Alma implementation for items#item

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#734]
GET      /items/:item_id(.:format)                 items#item {:format=>:json}
Investigate whether this endpoint is used. 

Alma does not provide this functionality. In order to get a single item from Alma we need the `bib_id`(`mms_id`) and `item_id`.

This is a new endpoint and we need a use case to support it before implementing.
 If we do this also add a form.

Possible implementation will use this Alma api endpoint.
https://developers.exlibrisgroup.com/console/?url=/wp-content/uploads/alma/openapi/bibs.json#/Catalog/get%2Falmaws%2Fv1%2Fbibs%2F%7Bmms_id%7D%2Fholdings%2F%7Bholding_id%7D%2Fitems

**Comment by jrgriffiniii** [comment]
I am sorry, I cannot readily find a solution for this without caching all of the bib. records, iterating through these, retrieving each of the `holding` resources for these, and then iterating through each `item`.

**Comment by jrgriffiniii** [comment]
I will proceed with looking at the Datadog and see about determining whether or not this endpoint is accessed frequently. Following a discussion during the daily check-in meeting held today, if this is infrequently accessed, there might not be a strong case for implementing a solution for this (or, even for removing the `ItemsController` entirely), given that, as christinach indicated, this really requires that the Alma API offer an entirely new endpoint.

**Comment by jrgriffiniii** [comment]
Throughout the past month, there has only been one request for this:
![image](https://user-images.githubusercontent.com/1443986/100918387-65ad3e00-34a6-11eb-8e50-6cd0e532c8f6.png)

**Comment by tpendragon** [comment]
That one request was probably me testing it a minute ago.

**Comment by jrgriffiniii** [comment]
@mzelesky, I hope that you do not mind me tagging you, however this issue addresses the ability for users to access Items by unique identifiers for https://bibdata.princeton.edu as we are looking to migrate to the Alma API:

![image](https://user-images.githubusercontent.com/1443986/100918950-26332180-34a7-11eb-89cf-b58c04f679ab.png)

As christinach discovered, there isn't currently an Alma API endpoint that would permit us to just query for Item records using *only* the Item ID (we would need to pass the bib. ID and holding ID for the Item as well). However, reviewing the usage metrics for bibdata.princeton.edu, it doesn't really appear as if users are using this on any regular basis.

Might you or any of your colleagues use this on any regular basis? Is there any reason to consider this essential to port to the Alma-based implementation of bibdata?

**Comment by mzelesky** [comment]
I personally don't use bibdata's APIs for any of my work, and I don't think anyone else in Enterprise Services uses it. It's possible some catalogers use it (specifically Don Thornbury or Tom Ventimiglia), but in Alma, it's entirely possible they'll be able to do whatever work uses this endpoint in Alma itself.

**Comment by jrgriffiniii** [comment]
Understood, thank you for confirming this @mzelesky.

**Comment by hackartisan** [comment]
This endpoint was removed per discussion of #654; closing.
