### ISSUE TITLE
Due date from Voyager should be formatted in this repo

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/marc_liberation#744]
This is the method in VoyagerHelpers that modifies the due date to null if the due date is more than 30 days ago.

https://github.com/pulibrary/voyager_helpers/blob/753232f8dd732d991aa95eaa08b6b475c2839549/lib/voyager_helpers/liberator.rb#L699

This logic should live in marc_liberation, for ease of moving to Alma.

**Comment by hackartisan** [comment]
Closing as a duplicate of #794
