### ISSUE TITLE
Implement alma functionality for bibliographic#bib_items

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#751]
GET /bibliographic/:bib_id/items(.:format) bibliographic#bib_items {:format=>:json}
Notes for providing `patron_group`:
/almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_id}/loans gives you the patron id, use it against the patron API to get the patron group (probably the `user_group` field). Note: don’t expose the patron ID from the marc_lib endpoint.

Also create the Alma form

**Comment by christinach** [comment]
https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/160Mapping_to_the_Normalized_Record/030Alma_MARC_21#Availability_Statuses_from_Alma

**Comment by christinach** [comment]
Items to compare
---1st ---
- https://bibdata.princeton.edu/bibliographic/731418/items
- mms_id: 99227515106421

--- 2nd ---
- https://bibdata.princeton.edu/bibliographic/31303/items
- mms_id: 99224836506421

**Comment by hackartisan** [comment]
Initial implementation is done; lots of follow-up; issues exist
