### ISSUE TITLE
More specific roles

### ISSUE THREAD

**Issue by tampakis** [pulibrary/marc_liberation#78]
`author_display` - default value "creator", more specific label may appear in `marc_relator_display`
`related_name_json_1display` - hash of roles to values, default value "Related name" (map over to contributor?)

Here is the mapping of relator codes to label: https://github.com/pulibrary/marc_liberation/blob/development/translation_maps/relators.rb

Some relator labels are outside of that above controlled list (catalogers sometimes encode the relator label directly instead of code) so we might want to filter those custom labels out.

**Comment by escowles** [comment]
Closed with #94
