### ISSUE TITLE
Translation from Voyager locations to Alma locations.

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#782]
Close this ticket when final spreadsheet exists in the google drive. Add google spreadsheet link here.

**Comment by pmgreen** [comment]
Preliminary mappings have been drafted. In review.

**Comment by mzelesky** [comment]
Here is the current Voyager to Alma mapping: https://docs.google.com/spreadsheets/d/18YCL_PoGMjybNHplVpVhdk-fEgPrTHHxU2VvNcpOTBI/edit?usp=sharing
