### ISSUE TITLE
Create a Rake task to read in the access list from a file and update the table

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/marc_liberation#789]
refs https://github.com/pulibrary/requests/issues/822

depends on #788

**Comment by kevinreiss** [comment]
How to identify a valid user:

1. The Course Title field value should be either "Safe Practices for Resumption of On-Campus Operations" or "Fall 2020 COVID-19 Training For Undergraduate and Graduate Students"
2. The On Campus Indictor field is "Y". 
3. Once the list of row has been filter by the values in (1) and (2) we can then de-duplicate them based on the "User Name" column to obtain the list of netids.

**Comment by kevinreiss** [comment]
I have asked for clarification on what we should do in instances where we have a duplicate netid with one row with On Campus marked "Y" and another row with it marked "N".
