### ISSUE TITLE
Full index from Alma

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#807]
Update: A lot of work has been done here and I think all we need now is a rake task.

The full index process will replicate the current process from Voyager as much as possible, in order to reuse our current indexing (traject) code to the fullest extent.

Dependencies:
- Depends on https://github.com/pulibrary/marc_liberation/issues/806 but the fields that need to be updated for alma could be commented-out while working this issue.
- Deployment depends on #859 but code could be developed and tested against a manually-created dump event

Requirements:

- We cannot use MARC21 file dumps provided daily from Alma because the data integrity is not good (see #731). We must use MARCXML records.
- Once it's indexed the full dump files, it should index each incremental update file published after the full dump was created.
- It should be initiated manually via a rake task and documented in https://docs.google.com/document/d/1bHvgfgyUmDXV7ROqEZFaRxJFEYhSSUbeQoQT883GMWg/edit.

**Comment by hackmastera** [comment]
Alma sandbox is at https://sandbox02-na.alma.exlibrisgroup.com/. credentials are in lastpass.

**Comment by hackmastera** [comment]
We have publishing profiles called "FTP Dump" (the full dump) and "Incremental Dump".

We can't schedule anything until January. At that point we're thinking we'll schedule it monthly.

We are exporting in XML because binary marc has a length limit. Try the binary export to see what happens if a record is too large?

configuration (click gears) - search for "integration profiles" to see webhook configuration.

**Comment by hackartisan** [comment]
We were going to try marc21 but we're not going to. leaving this here for posterity:

We are exporting in XML because binary marc has a length limit. 

Try the binary export to see what happens if a record is too large? No. Binary records aren't good.

There are some very large MARC records in our Alma right now. Here are the MMS IDs:

- 99222417706421 (102,439 bytes) (https://catalog.princeton.edu/catalog/627005 in Voyager -- So the bib record itself is quite small; there are just a lot of items, and Alma publishing adds a field for every item attached.)
- 9927882200521 (84,154 bytes)

**Comment by tpendragon** [comment]
I'm able to index -something- from the Alma dump files now, at least. The biggest immediate warnings that appear are for missing location codes.
