### ISSUE TITLE
Incremental index from Alma

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#809]
depends on #927

Incremental indexing will use the periodic file dumps produced by Alma. Files are created for records added deleted. This code also needs to delete suppressed records from the index. https://github.com/pulibrary/marc_liberation/issues/824 

Implementation:

- Update file frequency should be set at "the every 6 hours" (4am, 10am, 4pm, 10pm) option. This most closely matches our current 3x/day schedule.
- Build on work done in #927 such that once the dump files are created, they are indexed.

Considerations:

- There is an hourly update option available, but we're not sure if our updates ever take longer than an hour. We decided to use the "every 6 hours" option to avoid investigating questions about conflicting incremental updates for now.
- If conflicting incremental updates are a concern, only one incremental index should be allowed to run at a time to avoid a scenario where:
  - a long-running index job starts
  - a more recent, but smaller, dump is created and starts to index
  - the long-running / older index job overwrites an update made by the more recent job with older data.

Outstanding questions:

* How are deleted records discerned from the Alma file dumps?
  * Deleted records are included in the same file as new and updated records; most likely deletion will be marked by position 5 of the leader of the MARC record being 'd' (https://www.loc.gov/marc/bibliographic/bdleader.html)
  * Confirm the above! I (@hackartisan) thought I saw filenames suggesting that added and deleted records were grouped in separate files.
* Consider doing a bunch of API updates as part of end-to-end testing.

**Comment by hackmastera** [comment]
Proposal:

1. Move work from https://github.com/pulibrary/alma_experimentation/pull/8/files and  https://github.com/pulibrary/alma_experimentation/pull/33/files into `marc_liberation`.
1. Update the webhook handler. If the webhook action/event indicates an incremental dump job is complete, enqueue the event body to an AWS SQS FIFO queue.
1. Use the sidekiq cron gem https://github.com/ondrejbartas/sidekiq-cron to schedule a job to run every 15 minutes as follows: ```
Is this job is already running? ([example, see option 3](https://blog.francium.tech/avoiding-duplicate-jobs-in-sidekiq-dcbb1aca1e20))
  If so, terminate.
  If not, check the queue and if there's an event invoke the service that will create the Dump and Event objects and copy the files.
```

This should ensure that only one incremental job is processed at a time, and that they are processed in order.

**Comment by hectorcorrea** [comment]
Traject has newish/experimental support for deleting records

```
settings = {"solr.url": "http://localhost/solr"}
writer = Traject::SolrJsonWriter.new(settings)
id = "123"
writer.delete(id)
```

See [notes on Traject](https://github.com/traject/traject/issues/166) about this feature. The implementation is in https://github.com/traject/traject/blob/master/lib/traject/solr_json_writer.rb#L259-L281
