### ISSUE TITLE
JSONLD should have both free text and ISO 8601 dates

### ISSUE THREAD

**Issue by escowles** [pulibrary/marc_liberation#81]
dc:date = free text
dcterms:created = ISO 8601

**Comment by jpstroop** [comment]
It would be nice if you could just stick the data from the MARC 260, e.g. "Mainz : Gutenberg-Gesellschaft, 1926-", somewhere (it's `pub_created_display` in OL) in the dc (not terms). That would cover publisher and date the way users expect to see them and save formatting headaches.

**Comment by jpstroop** [comment]
Of course there are 10 different vocabs that model "publication event" (because that's what you'd really want) but none that leave space for a label.

**Comment by escowles** [comment]
I'm currently using the `pub_citation_display` which omits the date, but I'd be fine with switching to `pub_created_display` which includes it for `dc:publisher`.  Of course we could use some other vocab to model a publication event, but I think including the publication date in `dc:publisher` follows the spirit of the law.

**Comment by jpstroop** [comment]
> but I think including the publication date in dc:publisher follows the spirit of the law.

was afraid to suggest this, but maybe two wrongs in this case...

**Comment by escowles** [comment]
And how should we handle date ranges for dcterms:created?  EDTF?

**Comment by jpstroop** [comment]
ISO can do ranges, right? Just separate with a `/` I think?

**Comment by jpstroop** [comment]
Of course it would be nice if the spec were free, but https://en.wikipedia.org/wiki/ISO_8601#Time_intervals

**Comment by jpstroop** [comment]
Or https://www.w3.org/2006/time#, which is what the finding aids site does:

http://findingaids.princeton.edu/collections/AC044.rdf

**Comment by escowles** [comment]
I'd rather just separate the vaues with a `/` (I thought that was special to EDTF not part ISO 8601)

**Comment by jpstroop** [comment]
Yeah, I think so too.
