### ISSUE TITLE
Add a switch to traject to specify index source

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#822]
In traject.

Review the voyager helpers method https://github.com/pulibrary/voyager_helpers/blob/37b62ad83ed2f1af6185e54534d901e23e5fdf30/lib/voyager_helpers/liberator.rb#L959

Add a switch in the traject (a flag), and then update the rake task based on which indexing process we run. (daily index updates using an index job or force index update of a single bib using the controller endpoint #748).

**Comment by christinach** [comment]
**Single Records**
1. Get a single alma record https://developers.exlibrisgroup.com/console/?url=/wp-content/uploads/alma/openapi/bibs.json#/Catalog/get%2Falmaws%2Fv1%2Fbibs%2F%7Bmms_id%7D

1. If it has a `p_avail` (physical availability), get the list of items to get the `<creation_date>2020-06-01Z</creation_date> ` . Get the `creation_date` of the earliest item in the <items> list.

@mzelesky suggests that in Alma if there is a `p_avail` ignore the `e_avail` for determining catalog_date.

3. If there is no p_avail look if there is e_avail. We are not sure but we believe that we should use the `activation_date` for portfolios. https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_portfolio.xsd/

**Comment by christinach** [comment]
**Publishing profiles**
Bibliographic Enrichment -> Create date subfield 950b
Physical Items Enrichment -> Create date subfield 876d
Electronic Inventory Enrichment -> Activation date subfield 951w

1. Similar to the Single Record if there is a `876` field don't use the `951` fields. 
2. If there are no `876` or `951` then use the bib create date: Bibliographic Enrichment `950b`.

**Comment by hackartisan** [comment]
We decided instead to have bibliographic#update enhance marc records so that they work with the traject configuration already in place for the bib records coming from the alma publishing job.

**Comment by christinach** [comment]
related work https://github.com/pulibrary/bibdata/issues/926
