### ISSUE TITLE
Update locations and holding library in traject for Alma

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#823]
In voyager a location is in one subfield. In Alma the location is a combination of two subfields.

For Alma we will index the combination into a single location field.

It's `852|b` and `852|c`.

https://github.com/pulibrary/marc_liberation/blob/a691bf10e8f475172a586921d003f8f280329589/marc_to_solr/lib/traject_config.rb#L1111-L1115

holding library: 

https://github.com/pulibrary/marc_liberation/blob/a691bf10e8f475172a586921d003f8f280329589/marc_to_solr/lib/traject_config.rb#L1142

**Comment by hackartisan** [comment]
@christinach This issue says `852` but the comment in the file says `952` -- can you clarify?

**Comment by christinach** [comment]
@hackartisan This is something that @mzelesky wanted to review. @mzelesky or I will update the issue when there is a definite answer.

**Comment by christinach** [comment]
> @christinach This issue says `852` but the comment in the file says `952` -- can you clarify?

The `952 | b` and `952 | c` can be disregarded because we updated the publishing profile to put the 852 fields from the holdings in the records. 
Since bib records can have other 852 fields, we need to skip any 852 fields that do not have subfield 8 with a value that begins with 22 (prefix identifies as a holding record) and ends with the institution suffix (5 digits, currently 06421).

example:
```
852 0  $0 4148329 $b f $h HC1000 $i .O48 2001 
902    $a nv $b m $6 a $7 m $d v $f 1 $e 20050908 
904    $a nbs $b a $h n $c b $e 20030213 
950    $c 2020-07-23 14:45:06 US/Eastern $b 2020-05-27 16:32:31 US/Eastern $a false 
852 0  $b MAIN $c main $h HC1000 $i .O48 2001 $8 2281654580006421 
952    $d 2020-05-27 20:32:54 $8 2281654580006421 $a 2020-05-27 20:32:54 $b Main Library $c Stacks $e false 
876    $0 2281654580006421 $a 2381654560006421 $j 1 $i 0 $d 2020-05-27 20:32:54 $h HC1000 .O48 2001 $p 32101046019913
```
first 852 should be skipped because there is no subfield 8.

**Comment by christinach** [comment]
I'm blocking this issue until we have the full dump with production data and see what is included in the 852s.

**Comment by hackartisan** [comment]
blocked by #964

**Comment by hackartisan** [comment]
#964 has progressed enough to populate the table and therefore unblock this issue

**Comment by christinach** [comment]
there is an ongoing work for this one if someone else takes over. #1033
