### ISSUE TITLE
Add circ_group_id on the get_items_for_bib method

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#847]
child of #751 

What is a circ_group_id? This is used by voyager to determine the circulation policy. In voyager it's used in `circ_policy_group`

What values would it have? numerical

Is any code actually using this value? We think no. We checked
* orangelight
* requests
* marc_liberation
* voyager_helpers

**Comment by christinach** [comment]
blocked by #844

**Comment by hackartisan** [comment]
Given that we couldn't find any use of this field, we're closing this issue.

**Comment by mzelesky** [comment]
Isn't it used here?
https://github.com/pulibrary/voyager_helpers/blob/e468d9ae29367d74ba7e09620238e801a7ce7bad/lib/voyager_helpers/liberator.rb#L914

It determines pickup location. Not sure what that governs.
