### ISSUE TITLE
Add notes in the get_items_for_bib method

### ISSUE THREAD

**Issue by christinach** [pulibrary/marc_liberation#856]
child of #751 

This method is in `app/adapters/alma_adapter.rb` and used by the bibliographic controller.

Example call to bibliographic#bib_items:
https://bibdata.princeton.edu/bibliographic/426420/items

**Comment by christinach** [comment]
blocked by #844

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/marc_liberation/compare/alma...issues-856-jrgriffiniii-notes tracks an initial refactor for generating the JSON response for the BibliographicController#bib_items action

**Comment by eliotjordan** [comment]
Can pull from the bib record `AVA subcode='t'`

https://bibdata-alma-staging.princeton.edu/bibliographic/994304723506421
