### ISSUE TITLE
Remove trailing punctuation from titles in JSONLD

### ISSUE THREAD

**Issue by escowles** [pulibrary/marc_liberation#86]
Titles have trailing punctuation (typically ` /` but possibly others), which should be removed.  The regex `\s\p{P}$` should do the job.

**Comment by tampakis** [comment]
Based on the comment made by @jpstroop it sounds like we want to keep periods in.
 > some will end w/ abbreviations and shouldn't have the trailing stop stripped

**Comment by escowles** [comment]
Do we want trailing periods if there's a space before them?  I thought he was saying not to strip trailing periods from acronyms, abbreviations, etc.

**Comment by tampakis** [comment]
That sounds right. Duh, that's why you have the \s first

**Comment by tampakis** [comment]
`trim_punctuation` seems pretty sophisticated: https://github.com/traject/traject/blob/d6a23cc7ec5e22c0894927f8c9b9ce9b01a9f933/lib/traject/macros/marc21.rb#L216-L242

**Comment by tampakis** [comment]
The part about trimming periods only when the word before it has more than 4 characters seems like it will be right more often than it will be wrong.

**Comment by jpstroop** [comment]
Yup. Let's try it.
