### ISSUE TITLE
change master to main

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/marc_liberation#860]
https://jarv.is/notes/github-rename-master/

**Comment by hackmastera** [comment]
The process described in the link doesn't seem to mention open PRs or branch protection rules.

The script I've been using does take care of those things which is nice. More info on the orangelight issue: https://github.com/pulibrary/orangelight/issues/2210

**Comment by carolyncole** [comment]
@hackmastera Cool!  We were just closing or merging PRs prior to making the update.  Good to know the script exists.
