### ISSUE TITLE
Should we extract voyager_helpers?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/marc_liberation#92]
It already has its own gemspec, and would make it easier to reuse; would also make it possible to get marc_liberation's test coverage up, and further isolate the Voyager stuff that's tough to test.

**Comment by escowles** [comment]
Either way, we should stub out the Voyager calls in the marc_liberation tests so they can run in CI.  I'm plugging away at that and am down to 7 failures when I'm not connected.

**Comment by jpstroop** [comment]
Great! I can imagine that having that gem available without the overhead of the webapp might be useful to @garyleebuser and @pmgreen in particular. @kevinreiss, any thoughts about this?

**Comment by tampakis** [comment]
I think that the overhead of the webapp is nothing compared to the difficulties involved with getting the voyager_helpers configured, but extracting into a gem would help for reusability purposes. Not sure we need to pull it into a separate repo, but if we do then we can tell right away how plugin-able the gem is and test if marc_liberation can use it.

**Comment by jpstroop** [comment]
>  Not sure we need to pull it into a separate repo

That's really all I'm talking about. It's already a separate gem.

**Comment by kevinreiss** [comment]
Yes, I definitely agree @jpstroop. This would be useful for @garyleebuser, @mzelesky, and @pmgreen.

**Comment by jpstroop** [comment]
Closed by pulibrary/voyager_helpers#1
