### ISSUE TITLE
Update electronic access fields using the full dump

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#921]
Fields `electronic_access_1display` and `electronic_access_index` index 856 links to provide access to electronic content associated with a (usually print resource) record in the "online" section of the catalog show page.

https://github.com/pulibrary/marc_liberation/blob/a691bf10e8f475172a586921d003f8f280329589/marc_to_solr/lib/traject_config.rb#L326-L327

There's also some logic at the bottom:

https://github.com/pulibrary/marc_liberation/blob/a691bf10e8f475172a586921d003f8f280329589/marc_to_solr/lib/traject_config.rb#L1306-L1311

Example record with an 856 that we can use for a fixture: https://catalog-alma-qa.princeton.edu/catalog/9918573506421

**Comment by hackartisan** [comment]
blocked until locations are figured out

**Comment by christinach** [comment]
The proposal from @kevinreiss and @mzelesky is not to use umlaut on the record page like we currently do. But to query solr on the isbn, issn and oclc and populate the 'Online Section' in the record page relying on the indexed information. 

We will index the records using the information in the AVE tag, the 951 filed (electronic enrichment fields) and the 856.

**Comment by christinach** [comment]
As a start on this issue I will look into documenting Document the umlaut functionality #1034

**Comment by tpendragon** [comment]
So I think I've parsed this code mentally and, for 856s at least, I don't think we have to do anything.

**Comment by hackartisan** [comment]
@tpendragon that sounds right to me. Do you think we should replace any fixtures?

**Comment by tpendragon** [comment]
I think we're fine for the moment, it'll be faster if I just move to a new issue.

**Comment by hackartisan** [comment]
Okay! Can you submit a PR to close this issue that removes the relevant "TODO: change it in Alma" comments?
