### ISSUE TITLE
Update call_number_display in traject for Alma

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#923]
https://github.com/pulibrary/marc_liberation/blob/a691bf10e8f475172a586921d003f8f280329589/marc_to_solr/lib/traject_config.rb#L1262-L1265

**Comment by christinach** [comment]
Opened https://github.com/pulibrary/marc_liberation/issues/947 for the call_number_browse_s field

**Comment by christinach** [comment]
Feedback from @mzelesky for the call_number_display field.
`Subfield c currently is used as a sub-location. In Alma, subfield c is no longer part of the call number. Subfield k replaces the function of subfield c.`

**Comment by christinach** [comment]
closed by #948
