### ISSUE TITLE
Alma implementation for courses#index

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#931]
This controller action returns all the courses that have reserves.

Courses API documentation: https://developers.exlibrisgroup.com/alma/apis/courses/
- During investigation in the API dashboard we were getting an error and course lists weren't coming through
- Note this API requires pagination; returns max 100
- make sure to get 'ACTIVE' courses

The courses endpoint is documented as returning all data for each course: https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_courses.xsd/?tags=GET

Note there's a separate API key for courses.

See https://github.com/tulibraries/alma_rb/issues/62 for client library ticket.

**Comment by tpendragon** [comment]
We'll have to update the Alma client for this.

**Comment by hackartisan** [comment]
@tpendragon you mean alma-rb?

**Comment by tpendragon** [comment]
> @tpendragon you mean alma-rb?

Yes

**Comment by hackartisan** [comment]
@christinach has a start on work for alma_rb upstream. If someone else grabs this, she can point you to her branch.

**Comment by christinach** [comment]
Working on this using https://github.com/pulibrary/alma_rb/commit/4aafe40f5145257897ded4c56555b5643ee61d95

**Comment by christinach** [comment]
current bibdata courses fields.
{
"reserve_list_id": 8332,
"department_name": "Mathematics",
"department_code": "MAT",
"course_name": "Complex Analysis with Applications",
"course_number": "MAT 330",
"section_id": 0,
"instructor_first_name": "Javier",
"instructor_last_name": "Gómez-Serrano"
}]

Alma courses fields:
[{
"id": "2703155000006421",
"code": "000",
"name": "GSG",
"section": "",
"academic_department": {
"value": "GSG-246",
"desc": "GSG"
},
"processing_department": {
"value": "COURSE_UNIT",
"desc": "Course Unit"
},
"status": "ACTIVE",
"start_date": "2020-08-31Z",
"end_date": "2021-01-31Z",
"weekly_hours": 0,
"participants": 0,
"year": "",
"instructor": [],
"campus": [],
"note": [],
"created_by": "EX_LIBRIS",
"created_date": "2020-12-08Z",
"last_modified_by": "System",
"last_modified_date": "2020-12-08Z",
"rolled_from": "",
"link": "https://api-na.hosted.exlibrisgroup.com/almaws/v1/courses/2703155000006421"
}]

**Comment by christinach** [comment]
We added support for all courses in alma_rb gem.
This is blocked until further instructions.

**Comment by hackartisan** [comment]
Closing as wontfix; we can reopen if print reserves are reinstated.
