### ISSUE TITLE
Alma implementation for patron#patron_info

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#932]
This is used by the requests app.

example in live bibdata: 
https://bibdata.princeton.edu/patron/aheadley

```
{
netid: "auser",
first_name: "Alma",
last_name: "User",
barcode: "22101XXXXXXXXX",
barcode_status: 1,
barcode_status_date: "2017-09-28T23:00:01.000+00:00",
university_id: "00000000",
patron_group: "staff",
purge_date: "2021-10-31T23:00:03.000+00:00",
expire_date: "2022-10-31T23:00:03.000+00:00",
patron_id: 94462,
active_email: "person@example.com",
campus_authorized: false,
campus_authorized_category: "none"
}
```

Questions:
* will there still be a barcode? Yes. It's in the list of "user identifiers"

Alma documentation: https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_user.xsd/?tags=GET

Should be pretty straightforward. We should be able to use alma_rb.

Fields we don't think we are using:
- purge_stage
- expire_date
- barcode_status
- barcode_status_date

**Comment by pmgreen** [comment]
For user with barcode `123456789`:
`/almaws/v1/users/123456789?user_id_type=BARCODE`
`/almaws/v1/users/123456789?user_id_type=all_unique` [`all_unique` is default]

For user with primary identifier (could be netid) `NivA`:
`/almaws/v1/users/NivA?user_id_type=all_unique`
`/almaws/v1/users/NivA?user_id_type=PRIMARYIDENTIFIER` [this should work but it looks like ExL needs to activate user_type `PRIMARYIDENTIFIER`; could also define institution id `INST_ID`, etc.]

Full request URL is like e.g.:
`https://api-na.hosted.exlibrisgroup.com/almaws/v1/users/123456789?user_id_type=BARCODE&view=full&expand=none&apikey=foo`

**Comment by hackartisan** [comment]
Thanks for this @pmgreen. I tried messing searching for a user by primary identifier in the API console.  I found a user in Alma with a 'primary id' value populated, but the user didn't have any data in the "identifiers" tab. The API docs say that if you don't provide `user_id_type` then it will search all unique fields, but that didn't seen to work. When I used `user_id_type=PRIMARYIDENTIFIER` it told me I didn't have the right key. It seems like a key with user read/write permissions should work so I'm not sure what is going on there.

Seems like there are some things to work through just to get the API responding correctly once we start working on this issue.

**Comment by pmgreen** [comment]
@hackartisan I think `user_id_type=PRIMARYIDENTIFIER` isn't working right now because PRIMARYIDENTIFIER is not enabled as a user_id_type in our sandbox, and we can't toggle it to enabled with our admin user. It looks like ExL would have to enable it. [ExL docs](https://developers.exlibrisgroup.com/alma/integrations/user-management/) seem to suggest that we'll be able to configure this with migration, perhaps with the test migration available Jan 4? We may have to ask ExL unless @mzelesky or @kevinreiss know the answer.

**Comment by hackartisan** [comment]
With the production data I can get a record by barcode but I didn't have any success by netid.

**Comment by hackartisan** [comment]
You can't get an API response at all if there are no active barcodes

**Comment by hackartisan** [comment]
There's a user identifier type table in alma if you search for "user identifier types"

**Comment by hackartisan** [comment]
Outstanding data needs (@pmgreen will pursue these answers):
* Need netids in the records
* Need an entry in the user identifier types table tied to netids.

In the meantime we can work on this issue by obtaining fixtures using `user_id_type=BARCODE` with a barcode and/or `user_id_type=all_unique` with an institution id, then mocking them as responses to a request with `user_id_type=NETID`, which will possibly need to be updated once that's determined / in place.

**Comment by pmgreen** [comment]
NetIDs are currently in Alma as `user_title` (having migrated from `PATRON.TITLE`). To get netids into Alma as `NET_ID`, we need to run an SIS integration profile job, after data has been checked. Fulfillment staff are doing the methodical checks of patron records. If no issues have been found, ExL suggests that we could begin testing netids by adding some manually (identifiers tab in patron records).

**Comment by hackartisan** [comment]
We're going to update some individuals (folks in this department) to have the correct netid entries in their patron records so that we can use them for testing.

**Comment by pmgreen** [comment]
@hackartisan netids have been added to Alma user records for the DRDS and EUS teams
