### ISSUE TITLE
Alma implementation for barcode#scsb

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#933]
This endpoint is used when accessioning a new item. HTC (the company that supports scsb) has to find all the metadata.

from https://developers.exlibrisgroup.com/console/?url=/wp-content/uploads/alma/openapi/bibs.json#/Catalog/get:
Note: It is possible to retrieve item information by barcode using: GET /almaws/v1/items?item_barcode={item_barcode}. Calling this shorthand URL will return an HTTP 302 redirect response leading to a URL with the structure documented here.

This endpoint needs to return the actual (XML) MARC record with holding record.

The output record needs the holding information as well as item information (which only happens for ReCAP records - see https://github.com/pulibrary/voyager_helpers/blob/master/lib/voyager_helpers/liberator.rb#L1108-L1127 for how we do it in Voyager)

Example item to pull enrichment info for:

Voyager bib ID 7991903
Item barcode 32101089814220

Enrichments:

- [x] Holding ID
- [x] Item ID
- [x] Barcode
- [x] Copy Number
- [x] RECAP Use Restriction
- [x] RECAP Group Designation
- [x] RECAP Customer Code
- [x] Item Status (Blocked by #937 ?)  - @mzelesky confirmed that although it's a required subfield the value is not actually used, so it can be anything.
- [x] enum/cron (Need to understand this - Alma has several more of these than Voyager did, example would be good.)
- [x] Holding 852 (Do we need to get the entire holding MARC?)

**Comment by kevinreiss** [comment]
SCSB is not changing with respect to how this interface is used.

**Comment by tpendragon** [comment]
I'm having a tough time getting `/items` to work, it's just timing out for me.

**Comment by hackartisan** [comment]
Next step: contact exlibris either through basecamp or their support ticket system. start out with basecamp.

**Comment by hackartisan** [comment]
the api call works over `https`
