### ISSUE TITLE
Populate locations table and generate translation map from the Alma API

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#964]
Use the Alma locations API to get an initial population of the locations table.

Run as a rake task in a development instance, and then spin up the app development. Spinning up the app should generate `locations.rb`. 

For CI:
* Copy `locations.rb` to `locations.rb.tmpl`
* Also copy `location_display.rb.tmpl`
* Look into `holding_library.rb.tmpl` and see how this needs to be set up as well.

Blocking #823

**Comment by tpendragon** [comment]
`locations.rb` gets generated automatically at app spinup.

**Comment by hackartisan** [comment]
Updating language on this issue. We don't actually want a seeder because we don't want it to run in CI.
