### ISSUE TITLE
Reduce the set of unique identifiers in Alma

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#971]
The alma api, and by extension alma-rb, uses `user_id_type=all_unique` by default. It looks like our alma is configured to include facebook and twitter as unique identifiers, so it seems possible there could be a conflict between one of those values in a netid. We should try to reconfigure alma; otherwise we may want to explicitly use `BARCODE` and `NET_ID` when using the api. Revisit after #932 is done.

“The values that can be used are any of the values in the User Identifier Type code table.” -- this is the table we want updated to include just barcode, university id, and netid.

**Comment by pmgreen** [comment]
We're unable to edit user identifier types. Posted a request on BC for ExL to disable the social ids.

**Comment by pmgreen** [comment]
ExL updated the user id types table. Enabled ids:
```
INST_ID
BARCODE
NET_ID

**Comment by hackartisan** [comment]
Thanks @pmgreen!
