### ISSUE TITLE
What is the impact of a value change in patron group from id to code?

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#973]
It looks like bibdata provided the patron group ID from voyager. Alma provides what voyager considered the patron group code. 

See, e.g. https://github.com/pulibrary/voyager_helpers/blob/e468d9ae29367d74ba7e09620238e801a7ce7bad/lib/voyager_helpers/liberator.rb#L864

data from Alma:
```
user_group: {
value: "P",
desc: "P Faculty & Professional"
},
```

Data from voyager:
```
PATRON_GROUP_ID	PATRON_GROUP_CODE	PATRON_GROUP_NAME	        PATRON_GROUP_DISPLAY
3	            P	                P Faculty & Professional	Faculty and Professional Staff
```

Will this impact requests? Do we need to map the codes back to IDs so requests will continue to work?

**Comment by kevinreiss** [comment]
The patron_group appears only to be used by the recall request feature. 

https://github.com/pulibrary/requests/blob/175199ffbfe321ee1de86bce21f11bc78fd827dd/app/models/concerns/requests/voyager.rb#L27

Looks like it was a bit of boilerplate that the Voyager Recall Request API request. The Alma request endpoint doesn't look like it requires it. https://developers.exlibrisgroup.com/alma/apis/docs/bibs/UE9TVCAvYWxtYXdzL3YxL2JpYnMve21tc19pZH0vaG9sZGluZ3Mve2hvbGRpbmdfaWR9L2l0ZW1zL3tpdGVtX3BpZH0vcmVxdWVzdHM=/ it

**Comment by hackartisan** [comment]
@kevinreiss Sounds like no impact. Thanks!
