### ISSUE TITLE
Fatal traject error in make_time

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#993]
The full index errored before completing. Here is some output:

```
2021-01-20T23:35:46+00:00 ERROR 001 9958367833506421 - Missing holdings
2021-01-20T23:35:46+00:00 ERROR 001 9938582623506421 - Invalid Location Code: annex
2021-01-20T23:35:46+00:00 ERROR 001 9958367833506421 - Invalid Location Code: firestone
2021-01-20T23:35:46+00:00 ERROR 001 9924621233506421 - Missing holdings
2021-01-20T23:35:46+00:00 ERROR Unexpected error on record id `9938589053506421/9938589053506421` at file position 7349
    while executing (to_field cataloged_tdt at marc_to_solr/lib/traject_config.rb:292)
    Exception: ArgumentError: no time information in "W45 2002"
    /usr/lib/ruby/2.6.0/time.rb:194:in `make_time'

2021-01-20T23:35:46+00:00 ERROR 001 9924621233506421 - Invalid Location Code: rare
2021-01-20T23:35:46+00:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<ArgumentError: no time information in "W45 2002">
2021-01-20T23:35:46+00:00 ERROR 001 9938581813506421 - Missing holdings
/usr/lib/ruby/2.6.0/time.rb:194:in `make_time': no time information in "W45 2002" (ArgumentError)
        from /usr/lib/ruby/2.6.0/time.rb:375:in `parse'
        from marc_to_solr/lib/traject_config.rb:303:in `block (2 levels) in load_config_file'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer/step.rb:149:in `execute'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:346:in `block (2 levels) in map_to_context!'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:400:in `log_mapping_errors'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:345:in `block in map_to_context!'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:339:in `each'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:339:in `map_to_context!'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:474:in `block (2 levels) in process'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/abstract_executor_service.rb:92:in `handle_fallback'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:159:in `ns_execute'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_executor_service.rb:22:in `block in post'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_executor_service.rb:19:in `post'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/thread_pool.rb:108:in `maybe_in_thread_pool'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:473:in `block in process'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/marc-1.0.4/lib/marc/xml_parsers.rb:41:in `yield_record'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/marc-1.0.4/lib/marc/xml_parsers.rb:76:in `end_element_namespace'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:93:in `parse_with'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:93:in `parse_io'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/sax/parser.rb:81:in `parse'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/marc-1.0.4/lib/marc/xml_parsers.rb:116:in `each'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/marc_reader.rb:86:in `each'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:443:in `process'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/command_line.rb:67:in `execute'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/bin/traject:14:in `<top (required)>'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/bin/traject:23:in `load'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/bin/traject:23:in `<main>'
```

**Comment by christinach** [comment]
https://github.com/pulibrary/marc_liberation/blob/2c53da352247719e00113950503f7472e286ddbb/marc_to_solr/lib/traject_config.rb#L303

**Comment by hackartisan** [comment]
Looks like the file being indexed when this error happened was full_reindex_file_unzip_fulldump_6260333290006421_20210120_050120[007]_new_8320210120-17098-1dhtyfm.xml

**Comment by hackartisan** [comment]
Here's the record that was causing the error. I see from the code @christinach posted that 950b is expected to be a date. But it's a call number here. Not sure if the code is wrong or the export is messed up. @mzelesky?

[record_make_time_error.txt](https://github.com/pulibrary/marc_liberation/files/5869055/record_make_time_error.txt)

**Comment by christinach** [comment]
I looked again the enrichment fields and 950b is Create date. I'm not sure why there is a call number there.

**Comment by christinach** [comment]
there are two 950 fields in the record. the first one has |b the call number the second one has |b the date.

**Comment by christinach** [comment]
I checked the record that @hackartisan posted and it is a suppressed record. I'm not sure if it has something to do with the 950. `9938589053506421` but we should skip suppressed records while indexing.

**Comment by hackartisan** [comment]
@christinach It doesn't look suppressed to me. https://github.com/pulibrary/marc_liberation/issues/824 indicates that a suppressed record should have a '950$a' value of "Suppress from publishing Bibliographic Enrichment" This has a call number value in that subfield.

**Comment by christinach** [comment]
@hackartisan I mentioned in our meeting about a discrepancy in #824 regarding the suppressed. I see in https://princeton.alma.exlibrisgroup.com/ng/page;u=%2Frep%2Faction%2FpageAction.search.mms_results.xml.do%3FxmlFileName%3Dsearch.mms_results.xml&pageViewMode%3DEdit&pageBean.securityHashToken%3D-7577041729261673146 that  9938589053506421 is suppressed. @mzelesky can give us a better idea of what is going on with this record and with the content of issue #824

**Comment by christinach** [comment]
Based on the publishing profile details the 950 | a is as stated on #824 'Suppress from publishing subfield'. But I'm not sure yet why this record has a different value.

**Comment by christinach** [comment]
The second `950` field has in `|a` value 'true' which means that it is suppressed. Maybe the record is corrupted and shouldn't have the first 950.

**Comment by mzelesky** [comment]
So this is an example where there is a 950 field in the actual bib record that conflicts with the 950 created by the publishing enrichment.

I think the only real way to tackle this is to create a normalization process for catalogers that removes all fields from the bib record upon saving that the publishing job adds (950, 876, 852, 866, etc.), then run a periodic cleanup job on the records to remove those fields from records that missed the normalization.

So if there are traject errors related to unparseable fields (like the above fields), the best we can probably do is skip the record and report it out somehow. Otherwise you would have to add a lot of checking to remove fields that shouldn't be there.

One final note on this: it is possible to mark suppressed records as 'deleted' in the leader for the publishing job. This would be a more reliable way to exclude suppressed records than searching for a 950 field. This particular record is suppressed.

**Comment by hackartisan** [comment]
Okay skip it and report it is what we've done here in #1002 so I'm going to close this issue. The suppressed discussion should take place on #824. We'll talk about it at checkin today and then I will update that issue.
