### ISSUE TITLE
Return bound-withs from barcode#scsb with desired format

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#996]
In voyager we get several records returned with the same 852 and 876. This is the desired output.
example:
https://bibdata.princeton.edu/barcode/32101066958685/scsb

In alma we just get the host bibliographic record. 

Our controller needs to use the 774 fields to get the 3 other records, add in the 852 and 876 data, and return all 3 records.

**Comment by christinach** [comment]
closed by #997
